version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: greenthumb-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-greenthumb_dev}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schemas:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - greenthumb-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: greenthumb-redis
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - greenthumb-network

  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenthumb-api
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-greenthumb_dev}
      - REDIS_URL=redis://redis:6379/0
      - APP_ENV=${APP_ENV:-development}
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - greenthumb-network

  # Celery Worker (for async tasks)
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenthumb-celery-worker
    command: celery -A backend.tasks.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-greenthumb_dev}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - greenthumb-network

  # Celery Beat (for scheduled tasks)
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: greenthumb-celery-beat
    command: celery -A backend.tasks.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-greenthumb_dev}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend:/app/backend
    depends_on:
      - redis
    networks:
      - greenthumb-network

  # Frontend (for future use)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: greenthumb-frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - API_URL=http://api:8000
  #   depends_on:
  #     - api
  #   networks:
  #     - greenthumb-network

volumes:
  postgres_data:
  redis_data:

networks:
  greenthumb-network:
    driver: bridge

