name: 'greenthumb_discovery'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'greenthumb_discovery'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  greenthumb_discovery:
    # Staging models - raw data transformations
    staging:
      +materialized: view
      +schema: staging
    
    # Mart models - business logic transformations
    marts:
      +materialized: table
      +schema: marts
      
      # Core business entities
      core:
        +materialized: table
      
      # Product-specific models
      products:
        +materialized: table

# Seeds configuration
seeds:
  greenthumb_discovery:
    +schema: seeds
    +quote_columns: false

# Snapshots configuration
snapshots:
  greenthumb_discovery:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

